# Generated by Django 5.0.3 on 2024-03-14 17:57

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=service.models.create_custom_path
            ),
        ),
    ]
